!pip install requests pandas

In [8]:
import requests
import pandas as pd

In [ ]:
shop = "forma-active-dev.myshopify.com"
token = "MY ACCESS TOKEN"

In [10]:
url = f"https://{"forma-active-dev.myshopify.com"}/admin/api/2024-01/orders.json?limit=5"

headers = {
    "X-Shopify-Access-Token": "MY ACCESS TOKEN" 
}

response = requests.get(url, headers=headers)

print(response.status_code)
print(response.json())

200

In [11]:
data = response.json()
orders = data["orders"]

print(len(orders))
print(orders[0].keys())

5
dict_keys(['id', 'admin_graphql_api_id', 'app_id', 'browser_ip', 'buyer_accepts_marketing', 'cancel_reason', 'cancelled_at', 'cart_token', 'checkout_id', 'checkout_token', 'client_details', 'closed_at', 'company', 'confirmation_number', 'confirmed', 'created_at', 'currency', 'current_subtotal_price', 'current_subtotal_price_set', 'current_total_additional_fees_set', 'current_total_discounts', 'current_total_discounts_set', 'current_total_duties_set', 'current_total_price', 'current_total_price_set', 'current_total_tax', 'current_total_tax_set', 'customer_locale', 'device_id', 'discount_codes', 'duties_included', 'estimated_taxes', 'financial_status', 'fulfillment_status', 'landing_site', 'landing_site_ref', 'location_id', 'merchant_business_entity_id', 'merchant_of_record_app_id', 'name', 'note', 'note_attributes', 'number', 'order_number', 'original_total_additional_fees_set', 'original_total_duties_set', 'payment_gateway_names', 'po_number', 'presentment_currency', 'processed_at', 'reference', 'referring_site', 'source_identifier', 'source_name', 'source_url', 'subtotal_price', 'subtotal_price_set', 'tags', 'tax_exempt', 'tax_lines', 'taxes_included', 'test', 'token', 'total_cash_rounding_payment_adjustment_set', 'total_cash_rounding_refund_adjustment_set', 'total_discounts', 'total_discounts_set', 'total_line_items_price', 'total_line_items_price_set', 'total_outstanding', 'total_price', 'total_price_set', 'total_shipping_price_set', 'total_tax', 'total_tax_set', 'total_tip_received', 'total_weight', 'updated_at', 'user_id', 'billing_address', 'customer', 'discount_applications', 'fulfillments', 'line_items', 'payment_terms', 'refunds', 'shipping_address', 'shipping_lines'])

In [12]:
df_orders = pd.json_normalize(orders)

df_orders.head()

,id,admin_graphql_api_id,app_id,browser_ip,buyer_accepts_marketing,cancel_reason,cancelled_at,cart_token,checkout_id,checkout_token,...,customer.default_address.country,customer.default_address.province_code,customer.default_address.country_code,customer.default_address.country_name,customer.default_address.default,shipping_address.province,shipping_address.country,shipping_address.country_code,shipping_address.province_code,company
0,6778146586698,gid://shopify/Order/6778146586698,1354745,46.96.36.200,False,None,None,None,46074513621066,d60e709acb1bf0c34c72b6784dd2fa73,...,Canada,None,CA,Canada,True,Ontario,Canada,CA,ON,NaN
1,6778146553930,gid://shopify/Order/6778146553930,1354745,46.96.36.200,False,None,None,None,46074513293386,c57ebc38391273fa0df82dd280c2081b,...,Canada,None,CA,Canada,True,None,Canada,CA,None,NaN
2,6778146324554,gid://shopify/Order/6778146324554,1354745,46.96.36.200,False,None,None,None,46074512736330,d8fb6cbf1fb9a306a020292cbc17f93e,...,Canada,None,CA,Canada,True,Ontario,Canada,CA,ON,NaN
3,6778146193482,gid://shopify/Order/6778146193482,1354745,46.96.36.200,False,None,None,None,46074512015434,8e36198744295f819a885fcb55f5eecb,...,Canada,None,CA,Canada,True,None,Canada,CA,None,NaN
4,6778145308746,gid://shopify/Order/6778145308746,1354745,46.96.36.200,False,None,None,None,46074508050506,ec44c6fcdc0d47b48834d8289753cc77,...,Canada,None,CA,Canada,True,None,Canada,CA,None,NaN

In [13]:
len(orders)

5

In [15]:
import requests

def fetch_all_orders(shop, token):
    url = f"https://{shop}/admin/api/2024-01/orders.json?limit=250&status=any"
    
    headers = {
        "X-Shopify-Access-Token": token
    }

    all_orders = []

    while url:
        response = requests.get(url, headers=headers)
        data = response.json()
        
        all_orders.extend(data.get("orders", []))
        
        link = response.headers.get("Link")
        
        if link and 'rel="next"' in link:
            next_url = [l.split(";")[0].strip("<> ") for l in link.split(",") if 'rel="next"' in l][0]
            url = next_url
        else:
            url = None

    return all_orders

In [16]:
orders = fetch_all_orders(shop, token)
len(orders)

10

In [17]:
import pandas as pd

df_orders = pd.json_normalize(orders)
df_orders.head()

,id,admin_graphql_api_id,app_id,browser_ip,buyer_accepts_marketing,cancel_reason,cancelled_at,cart_token,checkout_id,checkout_token,...,customer.default_address.country,customer.default_address.province_code,customer.default_address.country_code,customer.default_address.country_name,customer.default_address.default,shipping_address.province,shipping_address.country,shipping_address.country_code,shipping_address.province_code,company
0,6778146586698,gid://shopify/Order/6778146586698,1354745,46.96.36.200,False,None,None,None,46074513621066,d60e709acb1bf0c34c72b6784dd2fa73,...,Canada,None,CA,Canada,True,Ontario,Canada,CA,ON,NaN
1,6778146553930,gid://shopify/Order/6778146553930,1354745,46.96.36.200,False,None,None,None,46074513293386,c57ebc38391273fa0df82dd280c2081b,...,Canada,None,CA,Canada,True,None,Canada,CA,None,NaN
2,6778146324554,gid://shopify/Order/6778146324554,1354745,46.96.36.200,False,None,None,None,46074512736330,d8fb6cbf1fb9a306a020292cbc17f93e,...,Canada,None,CA,Canada,True,Ontario,Canada,CA,ON,NaN
3,6778146193482,gid://shopify/Order/6778146193482,1354745,46.96.36.200,False,None,None,None,46074512015434,8e36198744295f819a885fcb55f5eecb,...,Canada,None,CA,Canada,True,None,Canada,CA,None,NaN
4,6778145308746,gid://shopify/Order/6778145308746,1354745,46.96.36.200,False,None,None,None,46074508050506,ec44c6fcdc0d47b48834d8289753cc77,...,Canada,None,CA,Canada,True,None,Canada,CA,None,NaN

In [18]:
df_orders = pd.json_normalize(orders)

df_orders.shape

(10, 164)

In [21]:
df_orders = pd.json_normalize(orders)

df_orders.shape

(10, 164)

In [22]:
df_orders.columns.tolist()[:30]

['id',
 'admin_graphql_api_id',
 'app_id',
 'browser_ip',
 'buyer_accepts_marketing',
 'cancel_reason',
 'cancelled_at',
 'cart_token',
 'checkout_id',
 'checkout_token',
 'closed_at',
 'confirmation_number',
 'confirmed',
 'created_at',
 'currency',
 'current_subtotal_price',
 'current_total_additional_fees_set',
 'current_total_discounts',
 'current_total_duties_set',
 'current_total_price',
 'current_total_tax',
 'customer_locale',
 'device_id',
 'discount_codes',
 'duties_included',
 'estimated_taxes',
 'financial_status',
 'fulfillment_status',
 'landing_site',
 'landing_site_ref']

In [23]:
df_orders[["id", "created_at", "total_price"]].head()

              id                 created_at total_price
0  6778146586698  2026-04-24T05:43:55-04:00      735.91
1  6778146553930  2026-04-24T05:43:45-04:00     3215.75
2  6778146324554  2026-04-24T05:43:31-04:00      706.65
3  6778146193482  2026-04-24T05:43:17-04:00     1745.68
4  6778145308746  2026-04-24T05:42:05-04:00     1247.38

In [24]:
df_orders["created_at"] = pd.to_datetime(df_orders["created_at"])
df_orders["total_price"] = pd.to_numeric(df_orders["total_price"])

In [25]:
df_orders_clean = df_orders[[
    "id",
    "created_at",
    "total_price",
    "financial_status"
]]

In [26]:
line_items = []

for order in orders:
    for item in order.get("line_items", []):
        line_items.append({
            "order_id": order["id"],
            "product_id": item.get("product_id"),
            "variant_id": item.get("variant_id"),
            "title": item.get("title"),
            "quantity": item.get("quantity"),
            "price": item.get("price")
        })

df_line_items = pd.DataFrame(line_items)
df_line_items.head()

,order_id,product_id,variant_id,title,quantity,price
0,6778146586698,8.189225e+12,4.353806e+13,The Multi-location Snowboard,1,705.19
1,6778146553930,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.92
2,6778146553930,8.189225e+12,4.353806e+13,The 3p Fulfilled Snowboard,1,2539.83
3,6778146324554,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.93
4,6778146193482,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.92

In [27]:
df_line_items["price"] = pd.to_numeric(df_line_items["price"])
df_line_items["quantity"] = pd.to_numeric(df_line_items["quantity"])

df_line_items["revenue"] = df_line_items["price"] * df_line_items["quantity"]

df_line_items[["revenue"]].sum()

revenue    15455.22
dtype: float64

In [28]:
product_perf = df_line_items.groupby("title").agg(
    total_revenue=("revenue", "sum"),
    units_sold=("quantity", "sum"),
    orders=("order_id", "nunique")
).reset_index()

product_perf.sort_values("total_revenue", ascending=False)

                          title  total_revenue  units_sold  orders
2        The Complete Snowboard       10234.93          15       6
1    The 3p Fulfilled Snowboard        2539.83           1       1
3         The Minimal Snowboard        1771.90           2       2
4  The Multi-location Snowboard         705.19           1       1
0              Custom Snowboard         203.37           1       1

In [29]:
df_orders_small = df_orders[["id", "created_at", "total_price"]]

customer_view = df_orders_small.rename(columns={"id": "order_id"}).merge(
    df_line_items,
    on="order_id",
    how="inner"
)

customer_view.head()

,order_id,created_at,total_price,product_id,variant_id,title,quantity,price,revenue
0,6778146586698,2026-04-24 05:43:55-04:00,735.91,8.189225e+12,4.353806e+13,The Multi-location Snowboard,1,705.19,705.19
1,6778146553930,2026-04-24 05:43:45-04:00,3215.75,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.92,675.92
2,6778146553930,2026-04-24 05:43:45-04:00,3215.75,8.189225e+12,4.353806e+13,The 3p Fulfilled Snowboard,1,2539.83,2539.83
3,6778146324554,2026-04-24 05:43:31-04:00,706.65,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.93,675.93
4,6778146193482,2026-04-24 05:43:17-04:00,1745.68,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.92,675.92

In [30]:
customer_view["month"] = customer_view["created_at"].dt.to_period("M")

monthly_revenue = customer_view.groupby("month").agg(
    revenue=("revenue", "sum")
).reset_index()

monthly_revenue

C:\Users\user\AppData\Local\Temp\ipykernel_8824\3837858840.py:1: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  customer_view["month"] = customer_view["created_at"].dt.to_period("M")

     month   revenue
0  2026-04  15455.22

In [31]:
orders_clean = df_orders[["id", "created_at", "total_price"]].drop_duplicates()

orders_clean.head()

              id                created_at  total_price
0  6778146586698 2026-04-24 05:43:55-04:00       735.91
1  6778146553930 2026-04-24 05:43:45-04:00      3215.75
2  6778146324554 2026-04-24 05:43:31-04:00       706.65
3  6778146193482 2026-04-24 05:43:17-04:00      1745.68
4  6778145308746 2026-04-24 05:42:05-04:00      1247.38

In [32]:
orders_clean = orders_clean.rename(columns={"id": "order_id"})

In [33]:
final_fact_table = df_line_items.merge(
    orders_clean,
    on="order_id",
    how="left"
)

final_fact_table.head()

,order_id,product_id,variant_id,title,quantity,price,revenue,created_at,total_price
0,6778146586698,8.189225e+12,4.353806e+13,The Multi-location Snowboard,1,705.19,705.19,2026-04-24 05:43:55-04:00,735.91
1,6778146553930,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.92,675.92,2026-04-24 05:43:45-04:00,3215.75
2,6778146553930,8.189225e+12,4.353806e+13,The 3p Fulfilled Snowboard,1,2539.83,2539.83,2026-04-24 05:43:45-04:00,3215.75
3,6778146324554,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.93,675.93,2026-04-24 05:43:31-04:00,706.65
4,6778146193482,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.92,675.92,2026-04-24 05:43:17-04:00,1745.68

In [34]:
final_fact_table["revenue"].sum()

np.float64(15455.22)

In [35]:
final_fact_table["order_month"] = final_fact_table["created_at"].dt.to_period("M")

C:\Users\user\AppData\Local\Temp\ipykernel_8824\1934415306.py:1: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  final_fact_table["order_month"] = final_fact_table["created_at"].dt.to_period("M")

In [36]:
customer_first_purchase = final_fact_table.groupby("order_id")["created_at"].min().reset_index()

customer_first_purchase["cohort_month"] = customer_first_purchase["created_at"].dt.to_period("M")

customer_first_purchase.head()

C:\Users\user\AppData\Local\Temp\ipykernel_8824\451871641.py:3: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  customer_first_purchase["cohort_month"] = customer_first_purchase["created_at"].dt.to_period("M")

        order_id                created_at cohort_month
0  6778144227402 2026-04-24 05:40:25-04:00      2026-04
1  6778144358474 2026-04-24 05:40:47-04:00      2026-04
2  6778144620618 2026-04-24 05:41:13-04:00      2026-04
3  6778144981066 2026-04-24 05:41:40-04:00      2026-04
4  6778145079370 2026-04-24 05:41:56-04:00      2026-04

In [37]:
final_fact_table = final_fact_table.merge(
    customer_first_purchase[["order_id", "cohort_month"]],
    on="order_id",
    how="left"
)

final_fact_table.head()

,order_id,product_id,variant_id,title,quantity,price,revenue,created_at,total_price,order_month,cohort_month
0,6778146586698,8.189225e+12,4.353806e+13,The Multi-location Snowboard,1,705.19,705.19,2026-04-24 05:43:55-04:00,735.91,2026-04,2026-04
1,6778146553930,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.92,675.92,2026-04-24 05:43:45-04:00,3215.75,2026-04,2026-04
2,6778146553930,8.189225e+12,4.353806e+13,The 3p Fulfilled Snowboard,1,2539.83,2539.83,2026-04-24 05:43:45-04:00,3215.75,2026-04,2026-04
3,6778146324554,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.93,675.93,2026-04-24 05:43:31-04:00,706.65,2026-04,2026-04
4,6778146193482,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.92,675.92,2026-04-24 05:43:17-04:00,1745.68,2026-04,2026-04

In [38]:
cohort_table = final_fact_table.groupby(["cohort_month", "order_month"]).agg(
    revenue=("revenue", "sum")
).reset_index()

cohort_table

  cohort_month order_month   revenue
0      2026-04     2026-04  15455.22

In [39]:
import numpy as np

expanded = []

for i in range(300):
    row = final_fact_table.sample(1).iloc[0].copy()
    
    row["order_id"] = f"SIM-{i}"
    row["quantity"] = np.random.randint(1, 4)
    row["price"] = row["price"] * np.random.uniform(0.8, 1.3)
    row["revenue"] = row["price"] * row["quantity"]
    
    # spread dates over time
    row["created_at"] = row["created_at"] + pd.to_timedelta(np.random.randint(0, 90), unit="D")
    
    expanded.append(row)

df_expanded = pd.DataFrame(expanded)

df_expanded.shape

(300, 11)

In [40]:
df_expanded["order_month"] = df_expanded["created_at"].dt.to_period("M")
df_expanded["cohort_month"] = df_expanded["cohort_month"].astype(str)

C:\Users\user\AppData\Local\Temp\ipykernel_8824\2271280789.py:1: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df_expanded["order_month"] = df_expanded["created_at"].dt.to_period("M")

In [41]:
cohort_table = df_expanded.groupby(["cohort_month", "order_month"]).agg(
    revenue=("revenue", "sum")
).reset_index()

In [42]:
df_expanded.shape

(300, 11)

In [43]:
df_expanded["order_id"].nunique()

300

In [44]:
df_expanded.to_csv("order_line_items_clean.csv", index=False)

In [45]:
customer_view.to_csv("customer_cohort.csv", index=False)

In [46]:
df_expanded.shape

(300, 11)

In [47]:
df_expanded.groupby("order_id").size().sort_values(ascending=False).head()

order_id
SIM-0      1
SIM-284    1
SIM-282    1
SIM-281    1
SIM-280    1
dtype: int64

In [48]:
df_orders.head()

,id,admin_graphql_api_id,app_id,browser_ip,buyer_accepts_marketing,cancel_reason,cancelled_at,cart_token,checkout_id,checkout_token,...,customer.default_address.country,customer.default_address.province_code,customer.default_address.country_code,customer.default_address.country_name,customer.default_address.default,shipping_address.province,shipping_address.country,shipping_address.country_code,shipping_address.province_code,company
0,6778146586698,gid://shopify/Order/6778146586698,1354745,46.96.36.200,False,None,None,None,46074513621066,d60e709acb1bf0c34c72b6784dd2fa73,...,Canada,None,CA,Canada,True,Ontario,Canada,CA,ON,NaN
1,6778146553930,gid://shopify/Order/6778146553930,1354745,46.96.36.200,False,None,None,None,46074513293386,c57ebc38391273fa0df82dd280c2081b,...,Canada,None,CA,Canada,True,None,Canada,CA,None,NaN
2,6778146324554,gid://shopify/Order/6778146324554,1354745,46.96.36.200,False,None,None,None,46074512736330,d8fb6cbf1fb9a306a020292cbc17f93e,...,Canada,None,CA,Canada,True,Ontario,Canada,CA,ON,NaN
3,6778146193482,gid://shopify/Order/6778146193482,1354745,46.96.36.200,False,None,None,None,46074512015434,8e36198744295f819a885fcb55f5eecb,...,Canada,None,CA,Canada,True,None,Canada,CA,None,NaN
4,6778145308746,gid://shopify/Order/6778145308746,1354745,46.96.36.200,False,None,None,None,46074508050506,ec44c6fcdc0d47b48834d8289753cc77,...,Canada,None,CA,Canada,True,None,Canada,CA,None,NaN

In [49]:
orders[0]

{'id': 6778146586698,
 'admin_graphql_api_id': 'gid://shopify/Order/6778146586698',
 'app_id': 1354745,
 'browser_ip': '46.96.36.200',
 'buyer_accepts_marketing': False,
 'cancel_reason': None,
 'cancelled_at': None,
 'cart_token': None,
 'checkout_id': 46074513621066,
 'checkout_token': 'd60e709acb1bf0c34c72b6784dd2fa73',
 'client_details': {'accept_language': None,
  'browser_height': None,
  'browser_ip': '46.96.36.200',
  'browser_width': None,
  'session_hash': None,
  'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36'},
 'closed_at': None,
 'company': {'id': 8654553162, 'location_id': 12451479626},
 'confirmation_number': 'ULXVY3QEK',
 'confirmed': True,
 'created_at': '2026-04-24T05:43:55-04:00',
 'currency': 'USD',
 'current_subtotal_price': '705.19',
 'current_subtotal_price_set': {'shop_money': {'amount': '705.19',
   'currency_code': 'USD'},
  'presentment_money': {'amount': '964.00', 'currency_code': 'CAD'}},
 'current_total_additional_fees_set': None,
 'current_total_discounts': '0.00',
 'current_total_discounts_set': {'shop_money': {'amount': '0.00',
   'currency_code': 'USD'},
  'presentment_money': {'amount': '0.00', 'currency_code': 'CAD'}},
 'current_total_duties_set': None,
 'current_total_price': '735.91',
 'current_total_price_set': {'shop_money': {'amount': '735.91',
   'currency_code': 'USD'},
  'presentment_money': {'amount': '1006.00', 'currency_code': 'CAD'}},
 'current_total_tax': '0.00',
 'current_total_tax_set': {'shop_money': {'amount': '0.00',
   'currency_code': 'USD'},
  'presentment_money': {'amount': '0.00', 'currency_code': 'CAD'}},
 'customer_locale': 'en',
 'device_id': None,
 'discount_codes': [],
 'duties_included': False,
 'estimated_taxes': False,
 'financial_status': 'paid',
 'fulfillment_status': None,
 'landing_site': None,
 'landing_site_ref': None,
 'location_id': None,
 'merchant_business_entity_id': '25363775562',
 'merchant_of_record_app_id': None,
 'name': '#1010',
 'note': None,
 'note_attributes': [],
 'number': 10,
 'order_number': 1010,
 'original_total_additional_fees_set': None,
 'original_total_duties_set': None,
 'payment_gateway_names': ['manual'],
 'po_number': None,
 'presentment_currency': 'CAD',
 'processed_at': '2026-04-24T05:43:54-04:00',
 'reference': None,
 'referring_site': None,
 'source_identifier': None,
 'source_name': 'shopify_draft_order',
 'source_url': None,
 'subtotal_price': '705.19',
 'subtotal_price_set': {'shop_money': {'amount': '705.19',
   'currency_code': 'USD'},
  'presentment_money': {'amount': '964.00', 'currency_code': 'CAD'}},
 'tags': 'Shipping Discount',
 'tax_exempt': False,
 'tax_lines': [],
 'taxes_included': False,
 'test': False,
 'token': '907657c2b5a72ab6cb6f8c85b1efd72b',
 'total_cash_rounding_payment_adjustment_set': {'shop_money': {'amount': '0.00',
   'currency_code': 'USD'},
  'presentment_money': {'amount': '0.00', 'currency_code': 'CAD'}},
 'total_cash_rounding_refund_adjustment_set': {'shop_money': {'amount': '0.00',
   'currency_code': 'USD'},
  'presentment_money': {'amount': '0.00', 'currency_code': 'CAD'}},
 'total_discounts': '0.00',
 'total_discounts_set': {'shop_money': {'amount': '0.00',
   'currency_code': 'USD'},
  'presentment_money': {'amount': '0.00', 'currency_code': 'CAD'}},
 'total_line_items_price': '705.19',
 'total_line_items_price_set': {'shop_money': {'amount': '705.19',
   'currency_code': 'USD'},
  'presentment_money': {'amount': '964.00', 'currency_code': 'CAD'}},
 'total_outstanding': '0.00',
 'total_price': '735.91',
 'total_price_set': {'shop_money': {'amount': '735.91',
   'currency_code': 'USD'},
  'presentment_money': {'amount': '1006.00', 'currency_code': 'CAD'}},
 'total_shipping_price_set': {'shop_money': {'amount': '30.72',
   'currency_code': 'USD'},
  'presentment_money': {'amount': '42.00', 'currency_code': 'CAD'}},
 'total_tax': '0.00',
 'total_tax_set': {'shop_money': {'amount': '0.00', 'currency_code': 'USD'},
  'presentment_money': {'amount': '0.00', 'currency_code': 'CAD'}},
 'total_tip_received': '0.00',
 'total_weight': 0,
 'updated_at': '2026-04-24T05:43:55-04:00',
 'user_id': None,
 'billing_address': {'province': None,
  'country': 'Canada',
  'country_code': 'CA',
  'province_code': None},
 'customer': {'id': 9704049770570,
  'created_at': '2026-04-24T05:31:22-04:00',
  'updated_at': '2026-04-24T05:43:55-04:00',
  'state': 'disabled',
  'note': None,
  'verified_email': True,
  'multipass_identifier': None,
  'tax_exempt': False,
  'email_marketing_consent': {'state': 'not_subscribed',
   'opt_in_level': 'single_opt_in',
   'consent_updated_at': None},
  'sms_marketing_consent': {'state': 'not_subscribed',
   'opt_in_level': 'single_opt_in',
   'consent_updated_at': None,
   'consent_collected_from': None},
  'tags': '',
  'currency': 'CAD',
  'tax_exemptions': [],
  'admin_graphql_api_id': 'gid://shopify/Customer/9704049770570',
  'default_address': {'id': 10302648549450,
   'customer_id': 9704049770570,
   'company': None,
   'province': None,
   'country': 'Canada',
   'province_code': None,
   'country_code': 'CA',
   'country_name': 'Canada',
   'default': True}},
 'discount_applications': [],
 'fulfillments': [],
 'line_items': [{'id': 16345780813898,
   'admin_graphql_api_id': 'gid://shopify/LineItem/16345780813898',
   'attributed_staffs': [],
   'current_quantity': 1,
   'fulfillable_quantity': 1,
   'fulfillment_service': 'manual',
   'fulfillment_status': None,
   'gift_card': False,
   'grams': 0,
   'name': 'The Multi-location Snowboard',
   'price': '705.19',
   'price_set': {'shop_money': {'amount': '705.19', 'currency_code': 'USD'},
    'presentment_money': {'amount': '964.00', 'currency_code': 'CAD'}},
   'product_exists': True,
   'product_id': 8189224648778,
   'properties': [],
   'quantity': 1,
   'requires_shipping': True,
   'sku': None,
   'taxable': True,
   'title': 'The Multi-location Snowboard',
   'total_discount': '0.00',
   'total_discount_set': {'shop_money': {'amount': '0.00',
     'currency_code': 'USD'},
    'presentment_money': {'amount': '0.00', 'currency_code': 'CAD'}},
   'variant_id': 43538059657290,
   'variant_inventory_management': 'shopify',
   'variant_title': None,
   'vendor': 'forma-active-dev',
   'tax_lines': [],
   'duties': [],
   'discount_allocations': []}],
 'payment_terms': None,
 'refunds': [],
 'shipping_address': {'province': 'Ontario',
  'country': 'Canada',
  'country_code': 'CA',
  'province_code': 'ON'},
 'shipping_lines': [{'id': 5721367642186,
   'carrier_identifier': None,
   'code': 'International Shipping',
   'discounted_price': '30.72',
   'discounted_price_set': {'shop_money': {'amount': '30.72',
     'currency_code': 'USD'},
    'presentment_money': {'amount': '42.00', 'currency_code': 'CAD'}},
   'is_removed': False,
   'phone': None,
   'price': '30.72',
   'price_set': {'shop_money': {'amount': '30.72', 'currency_code': 'USD'},
    'presentment_money': {'amount': '42.00', 'currency_code': 'CAD'}},
   'requested_fulfillment_service_id': None,
   'source': 'shopify',
   'title': 'International Shipping',
   'tax_lines': [],
   'discount_allocations': []}]}

In [51]:
line_items = []

for order in orders:
    for item in order["line_items"]:
        line_items.append({
            "order_id": order["id"],
            "created_at": order["created_at"],
            "customer_id": order.get("customer", {}).get("id"),
            "product_id": item.get("product_id"),
            "variant_id": item.get("variant_id"),
            "title": item.get("title"),
            "quantity": item.get("quantity"),
            "price": float(item.get("price", 0)),
            "revenue": float(item.get("price", 0)) * item.get("quantity", 1),
            "order_total": float(order.get("total_price", 0))
        })

df_fact = pd.DataFrame(line_items)

In [52]:
df_fact.shape

(12, 10)

In [53]:
df_fact["order_id"].nunique()

10

In [54]:
import numpy as np
import pandas as pd

# keep original safe copy
df_base = df_orders.copy()

# expand to ~300 rows (safe multiplier)
df_expanded = pd.concat([df_base] * 30, ignore_index=True)

df_expanded.shape

(300, 164)

In [55]:
df_expanded["order_id"] = "SIM-" + df_expanded.index.astype(str)

In [56]:
df_expanded["created_at"] = pd.to_datetime(df_expanded["created_at"])

df_expanded["created_at"] = df_expanded["created_at"] + pd.to_timedelta(
    np.random.randint(-72, 72, len(df_expanded)),
    unit="h"
)

In [57]:
df_expanded["total_price"] = pd.to_numeric(df_expanded["total_price"], errors="coerce")

In [58]:
df_expanded["revenue"] = df_expanded.get("revenue", df_expanded["total_price"])

In [59]:
print(df_expanded.shape)
print(df_expanded["order_id"].nunique())
print(df_expanded["total_price"].sum())
df_expanded.head()

(300, 166)
300
435469.2

,id,admin_graphql_api_id,app_id,browser_ip,buyer_accepts_marketing,cancel_reason,cancelled_at,cart_token,checkout_id,checkout_token,...,customer.default_address.country_code,customer.default_address.country_name,customer.default_address.default,shipping_address.province,shipping_address.country,shipping_address.country_code,shipping_address.province_code,company,order_id,revenue
0,6778146586698,gid://shopify/Order/6778146586698,1354745,46.96.36.200,False,None,None,None,46074513621066,d60e709acb1bf0c34c72b6784dd2fa73,...,CA,Canada,True,Ontario,Canada,CA,ON,NaN,SIM-0,735.91
1,6778146553930,gid://shopify/Order/6778146553930,1354745,46.96.36.200,False,None,None,None,46074513293386,c57ebc38391273fa0df82dd280c2081b,...,CA,Canada,True,None,Canada,CA,None,NaN,SIM-1,3215.75
2,6778146324554,gid://shopify/Order/6778146324554,1354745,46.96.36.200,False,None,None,None,46074512736330,d8fb6cbf1fb9a306a020292cbc17f93e,...,CA,Canada,True,Ontario,Canada,CA,ON,NaN,SIM-2,706.65
3,6778146193482,gid://shopify/Order/6778146193482,1354745,46.96.36.200,False,None,None,None,46074512015434,8e36198744295f819a885fcb55f5eecb,...,CA,Canada,True,None,Canada,CA,None,NaN,SIM-3,1745.68
4,6778145308746,gid://shopify/Order/6778145308746,1354745,46.96.36.200,False,None,None,None,46074508050506,ec44c6fcdc0d47b48834d8289753cc77,...,CA,Canada,True,None,Canada,CA,None,NaN,SIM-4,1247.38

In [60]:
fact_orders = df_expanded[[
    "order_id",
    "created_at",
    "customer.id",
    "total_price",
    "revenue",
    "financial_status",
    "shipping_address.country_code"
]].copy()

fact_orders.head()

,order_id,created_at,customer.id,total_price,revenue,financial_status,shipping_address.country_code
0,SIM-0,2026-04-21 23:43:55-04:00,9704049770570,735.91,735.91,paid,CA
1,SIM-1,2026-04-24 13:43:45-04:00,9704049803338,3215.75,3215.75,paid,CA
2,SIM-2,2026-04-27 00:43:31-04:00,9704049770570,706.65,706.65,paid,CA
3,SIM-3,2026-04-26 19:43:17-04:00,9704049803338,1745.68,1745.68,paid,CA
4,SIM-4,2026-04-26 14:42:05-04:00,9704049803338,1247.38,1247.38,paid,CA

In [61]:
product_fact = df_expanded[[
    "order_id",
    "product_id",
    "title",
    "quantity",
    "price",
    "revenue"
]].copy()

product_fact.head()

KeyError: "['product_id', 'title', 'quantity', 'price'] not in index"

In [62]:
# rebuild from original Shopify JSON structure
product_rows = []

for order in orders:
    for item in order.get("line_items", []):
        product_rows.append({
            "order_id": order["id"],
            "created_at": order["created_at"],
            "product_id": item.get("product_id"),
            "title": item.get("title"),
            "quantity": item.get("quantity"),
            "price": float(item.get("price", 0)),
            "revenue": float(item.get("price", 0)) * item.get("quantity", 1)
        })

product_fact = pd.DataFrame(product_rows)

product_fact.shape

(12, 7)

In [63]:
product_fact = pd.concat([product_fact] * 10, ignore_index=True)

In [64]:
product_fact["order_id"] = "SIM-" + product_fact.index.astype(str)

In [65]:
print("orders:", df_expanded.shape)
print("product_fact:", product_fact.shape)

orders: (300, 166)
product_fact: (120, 7)

In [66]:
orders_fact = df_expanded[[
    "order_id",
    "created_at",
    "customer.id",
    "total_price",
    "revenue",
    "financial_status",
    "shipping_address.country_code"
]].copy()

orders_fact["created_at"] = pd.to_datetime(orders_fact["created_at"])
orders_fact["order_month"] = orders_fact["created_at"].dt.to_period("M").astype(str)

orders_fact.shape

C:\Users\user\AppData\Local\Temp\ipykernel_8824\3573262461.py:12: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  orders_fact["order_month"] = orders_fact["created_at"].dt.to_period("M").astype(str)

(300, 8)

In [67]:
product_fact["order_id"] = product_fact["order_id"].astype(str)
orders_fact["order_id"] = orders_fact["order_id"].astype(str)

In [68]:
print("Orders:", orders_fact["order_id"].nunique())
print("Product rows:", product_fact["order_id"].nunique())
print("Join overlap:", len(set(product_fact["order_id"]).intersection(set(orders_fact["order_id"]))))

Orders: 300
Product rows: 120
Join overlap: 120

In [69]:
product_dim = product_fact[[
    "product_id",
    "title"
]].drop_duplicates()

product_dim.head()

      product_id                         title
0   8.189225e+12  The Multi-location Snowboard
1   8.189225e+12        The Complete Snowboard
2   8.189225e+12    The 3p Fulfilled Snowboard
8   8.189224e+12         The Minimal Snowboard
10           NaN              Custom Snowboard

In [70]:
customer_dim = df_expanded[[
    "customer.id",
    "shipping_address.country_code"
]].drop_duplicates()

customer_dim.head()

     customer.id shipping_address.country_code
0  9704049770570                            CA
1  9704049803338                            CA
6  9704074182730                            US

In [71]:
product_dim = product_dim.dropna(subset=["product_id"]).copy()

product_dim["product_id"] = product_dim["product_id"].astype("int64").astype(str)

product_dim.head()

      product_id                         title
0  8189224648778  The Multi-location Snowboard
1  8189224517706        The Complete Snowboard
2  8189224714314    The 3p Fulfilled Snowboard
8  8189224386634         The Minimal Snowboard

In [72]:
customer_dim = customer_dim.dropna(subset=["customer.id"]).copy()

customer_dim["customer.id"] = customer_dim["customer.id"].astype(str)

customer_dim.head()

     customer.id shipping_address.country_code
0  9704049770570                            CA
1  9704049803338                            CA
6  9704074182730                            US

In [73]:
product_fact["product_id"] = product_fact["product_id"].dropna().astype("int64").astype(str)

In [74]:
product_fact = product_fact.dropna(subset=["product_id", "title"])

In [75]:
print("Orders:", orders_fact.shape)
print("Products:", product_fact.shape)
print("Customers:", customer_dim.shape)

print("Null product IDs:", product_fact["product_id"].isna().sum())

Orders: (300, 8)
Products: (110, 7)
Customers: (3, 2)
Null product IDs: 0

In [76]:
df_expanded = df_orders.explode("line_items").reset_index(drop=True)

In [77]:
line_items = pd.json_normalize(df_expanded["line_items"])

In [78]:
df_expanded = df_expanded.drop(columns=["line_items"]).join(line_items)

ValueError: columns overlap but no suffix specified: Index(['id', 'admin_graphql_api_id', 'fulfillment_status', 'name',
       'tax_lines'],
      dtype='object')

In [79]:
line_items = pd.json_normalize(df_expanded["line_items"])

In [80]:
line_items = line_items[[
    "product_id",
    "variant_id",
    "title",
    "quantity",
    "price"
]]

In [81]:
df_expanded = pd.concat(
    [df_expanded.drop(columns=["line_items"]), line_items],
    axis=1
)

In [82]:
df_expanded.shape
df_expanded.head()
df_expanded.columns

Index(['id', 'admin_graphql_api_id', 'app_id', 'browser_ip',
       'buyer_accepts_marketing', 'cancel_reason', 'cancelled_at',
       'cart_token', 'checkout_id', 'checkout_token',
       ...
       'shipping_address.province', 'shipping_address.country',
       'shipping_address.country_code', 'shipping_address.province_code',
       'company', 'product_id', 'variant_id', 'title', 'quantity', 'price'],
      dtype='object', length=168)

In [83]:
fact_orders = df_expanded[[
    "id",
    "created_at",
    "customer.id",
    "product_id",
    "variant_id",
    "title",
    "quantity",
    "price",
    "current_total_price"
]].copy()

In [84]:
fact_orders = fact_orders.rename(columns={
    "id": "order_id",
    "customer.id": "customer_id"
})

In [85]:
fact_orders["revenue"] = fact_orders["quantity"] * fact_orders["price"].astype(float)

In [86]:
fact_orders["created_at"] = pd.to_datetime(fact_orders["created_at"])
fact_orders["order_month"] = fact_orders["created_at"].dt.to_period("M")

C:\Users\user\AppData\Local\Temp\ipykernel_8824\713136430.py:2: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  fact_orders["order_month"] = fact_orders["created_at"].dt.to_period("M")

In [87]:
print(fact_orders.shape)
print(fact_orders["order_id"].nunique())
print(fact_orders["revenue"].sum())

(12, 11)
10
15455.22

In [88]:
df_expanded.shape

(12, 168)

In [89]:
df_orders = pd.json_normalize(orders)
print(df_orders.shape)

(10, 164)

In [90]:
df_orders = pd.json_normalize(orders)
print(df_orders.shape)

(10, 164)

In [91]:
response = requests.get(url, headers=headers)
orders = response.json()["orders"]

In [92]:
len(orders)

5

In [93]:
final_fact_table = df_expanded.copy()

In [94]:
final_fact_table = final_fact_table[[
    "order_id",
    "created_at",
    "customer.id",
    "product_id",
    "variant_id",
    "title",
    "quantity",
    "price",
    "revenue",
    "total_price"
]]

KeyError: "['order_id', 'revenue'] not in index"

In [95]:
final_fact_table.columns

Index(['id', 'admin_graphql_api_id', 'app_id', 'browser_ip',
       'buyer_accepts_marketing', 'cancel_reason', 'cancelled_at',
       'cart_token', 'checkout_id', 'checkout_token',
       ...
       'shipping_address.province', 'shipping_address.country',
       'shipping_address.country_code', 'shipping_address.province_code',
       'company', 'product_id', 'variant_id', 'title', 'quantity', 'price'],
      dtype='object', length=168)

In [96]:
final_fact_table.columns

Index(['id', 'admin_graphql_api_id', 'app_id', 'browser_ip',
       'buyer_accepts_marketing', 'cancel_reason', 'cancelled_at',
       'cart_token', 'checkout_id', 'checkout_token',
       ...
       'shipping_address.province', 'shipping_address.country',
       'shipping_address.country_code', 'shipping_address.province_code',
       'company', 'product_id', 'variant_id', 'title', 'quantity', 'price'],
      dtype='object', length=168)

In [97]:
df_expanded.shape
df_expanded.columns

Index(['id', 'admin_graphql_api_id', 'app_id', 'browser_ip',
       'buyer_accepts_marketing', 'cancel_reason', 'cancelled_at',
       'cart_token', 'checkout_id', 'checkout_token',
       ...
       'shipping_address.province', 'shipping_address.country',
       'shipping_address.country_code', 'shipping_address.province_code',
       'company', 'product_id', 'variant_id', 'title', 'quantity', 'price'],
      dtype='object', length=168)

In [98]:
df_orders.columns

Index(['id', 'admin_graphql_api_id', 'app_id', 'browser_ip',
       'buyer_accepts_marketing', 'cancel_reason', 'cancelled_at',
       'cart_token', 'checkout_id', 'checkout_token',
       ...
       'customer.default_address.country',
       'customer.default_address.province_code',
       'customer.default_address.country_code',
       'customer.default_address.country_name',
       'customer.default_address.default', 'shipping_address.province',
       'shipping_address.country', 'shipping_address.country_code',
       'shipping_address.province_code', 'company'],
      dtype='object', length=164)

In [99]:
df_orders["line_items"].iloc[0]

[{'id': 16345780813898,
  'admin_graphql_api_id': 'gid://shopify/LineItem/16345780813898',
  'attributed_staffs': [],
  'current_quantity': 1,
  'fulfillable_quantity': 1,
  'fulfillment_service': 'manual',
  'fulfillment_status': None,
  'gift_card': False,
  'grams': 0,
  'name': 'The Multi-location Snowboard',
  'price': '705.19',
  'price_set': {'shop_money': {'amount': '705.19', 'currency_code': 'USD'},
   'presentment_money': {'amount': '964.00', 'currency_code': 'CAD'}},
  'product_exists': True,
  'product_id': 8189224648778,
  'properties': [],
  'quantity': 1,
  'requires_shipping': True,
  'sku': None,
  'taxable': True,
  'title': 'The Multi-location Snowboard',
  'total_discount': '0.00',
  'total_discount_set': {'shop_money': {'amount': '0.00',
    'currency_code': 'USD'},
   'presentment_money': {'amount': '0.00', 'currency_code': 'CAD'}},
  'variant_id': 43538059657290,
  'variant_inventory_management': 'shopify',
  'variant_title': None,
  'vendor': 'forma-active-dev',
  'tax_lines': [],
  'duties': [],
  'discount_allocations': []}]

In [100]:
import pandas as pd

line_items = pd.json_normalize(
    df_orders.to_dict(orient="records"),
    record_path="line_items",
    meta=["id", "created_at", "total_price"],
    errors="ignore"
)

ValueError: Conflicting metadata name id, need distinguishing prefix

In [101]:
import pandas as pd

line_items = pd.json_normalize(
    df_orders.to_dict(orient="records"),
    record_path="line_items",
    meta=["created_at", "total_price"],
    errors="ignore"
)

In [102]:
order_ids = df_orders["id"].repeat(df_orders["line_items"].apply(len)).values

line_items["order_id"] = order_ids

In [103]:
line_items[["order_id", "product_id", "title", "quantity", "price"]].head()

,order_id,product_id,title,quantity,price
0,6778146586698,8.189225e+12,The Multi-location Snowboard,1,705.19
1,6778146553930,8.189225e+12,The Complete Snowboard,1,675.92
2,6778146553930,8.189225e+12,The 3p Fulfilled Snowboard,1,2539.83
3,6778146324554,8.189225e+12,The Complete Snowboard,1,675.93
4,6778146193482,8.189225e+12,The Complete Snowboard,1,675.92

In [104]:
final_fact_table = line_items.copy()

In [105]:
final_fact_table["revenue"] = final_fact_table["price"].astype(float) * final_fact_table["quantity"]

In [106]:
final_fact_table = final_fact_table[[
    "order_id",
    "created_at",
    "product_id",
    "variant_id",
    "title",
    "quantity",
    "price",
    "revenue",
    "total_price"
]]

In [107]:
final_fact_table.shape
final_fact_table.head()

,order_id,created_at,product_id,variant_id,title,quantity,price,revenue,total_price
0,6778146586698,2026-04-24T05:43:55-04:00,8.189225e+12,4.353806e+13,The Multi-location Snowboard,1,705.19,705.19,735.91
1,6778146553930,2026-04-24T05:43:45-04:00,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.92,675.92,3215.75
2,6778146553930,2026-04-24T05:43:45-04:00,8.189225e+12,4.353806e+13,The 3p Fulfilled Snowboard,1,2539.83,2539.83,3215.75
3,6778146324554,2026-04-24T05:43:31-04:00,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.93,675.93,706.65
4,6778146193482,2026-04-24T05:43:17-04:00,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.92,675.92,1745.68

In [108]:
final_fact_table.shape

(12, 9)

In [109]:
orders_raw = df_orders.copy()

In [110]:
line_items = orders_raw.explode("line_items")

In [111]:

line_items = pd.concat(
    [
        line_items.drop(columns=["line_items"]).reset_index(drop=True),
        pd.json_normalize(line_items["line_items"])
    ],
    axis=1
)

In [112]:
line_items.shape
line_items.head()

,id,admin_graphql_api_id,app_id,browser_ip,buyer_accepts_marketing,cancel_reason,cancelled_at,cart_token,checkout_id,checkout_token,...,duties,discount_allocations,price_set.shop_money.amount,price_set.shop_money.currency_code,price_set.presentment_money.amount,price_set.presentment_money.currency_code,total_discount_set.shop_money.amount,total_discount_set.shop_money.currency_code,total_discount_set.presentment_money.amount,total_discount_set.presentment_money.currency_code
0,6778146586698,gid://shopify/Order/6778146586698,1354745,46.96.36.200,False,None,None,None,46074513621066,d60e709acb1bf0c34c72b6784dd2fa73,...,[],[],705.19,USD,964.00,CAD,0.00,USD,0.00,CAD
1,6778146553930,gid://shopify/Order/6778146553930,1354745,46.96.36.200,False,None,None,None,46074513293386,c57ebc38391273fa0df82dd280c2081b,...,[],[],675.92,USD,924.00,CAD,0.00,USD,0.00,CAD
2,6778146553930,gid://shopify/Order/6778146553930,1354745,46.96.36.200,False,None,None,None,46074513293386,c57ebc38391273fa0df82dd280c2081b,...,[],[],2539.83,USD,3472.00,CAD,0.00,USD,0.00,CAD
3,6778146324554,gid://shopify/Order/6778146324554,1354745,46.96.36.200,False,None,None,None,46074512736330,d8fb6cbf1fb9a306a020292cbc17f93e,...,[],[],675.93,USD,924.00,CAD,0.00,USD,0.00,CAD
4,6778146193482,gid://shopify/Order/6778146193482,1354745,46.96.36.200,False,None,None,None,46074512015434,8e36198744295f819a885fcb55f5eecb,...,[],"[{'amount': '10.16', 'amount_set': {'shop_mone...",675.92,USD,924.00,CAD,10.16,USD,13.89,CAD

In [113]:
import pandas as pd

line_items = pd.json_normalize(
    df_orders.to_dict(orient="records"),
    record_path="line_items",
    meta=[
        "id",
        "created_at",
        "total_price",
        "customer.id"
    ],
    errors="ignore"
)

ValueError: Conflicting metadata name id, need distinguishing prefix

In [114]:
df_orders_fixed = df_orders.copy()

df_orders_fixed["order_id"] = df_orders_fixed["id"]
df_orders_fixed["customer_id"] = df_orders_fixed["customer"].apply(
    lambda x: x["id"] if isinstance(x, dict) else None
)

KeyError: 'customer'

In [115]:
df_orders.columns

Index(['id', 'admin_graphql_api_id', 'app_id', 'browser_ip',
       'buyer_accepts_marketing', 'cancel_reason', 'cancelled_at',
       'cart_token', 'checkout_id', 'checkout_token',
       ...
       'customer.default_address.country',
       'customer.default_address.province_code',
       'customer.default_address.country_code',
       'customer.default_address.country_name',
       'customer.default_address.default', 'shipping_address.province',
       'shipping_address.country', 'shipping_address.country_code',
       'shipping_address.province_code', 'company'],
      dtype='object', length=164)

In [116]:
df_orders.head(1).T

                                                                0
id                                                  6778146586698
admin_graphql_api_id            gid://shopify/Order/6778146586698
app_id                                                    1354745
browser_ip                                           46.96.36.200
buyer_accepts_marketing                                     False
...                                                           ...
shipping_address.province                                 Ontario
shipping_address.country                                   Canada
shipping_address.country_code                                  CA
shipping_address.province_code                                 ON
company                                                       NaN

[164 rows x 1 columns]

In [117]:
df_orders.iloc[0]

id                                                    6778146586698
admin_graphql_api_id              gid://shopify/Order/6778146586698
app_id                                                      1354745
browser_ip                                             46.96.36.200
buyer_accepts_marketing                                       False
                                                ...
shipping_address.province                                   Ontario
shipping_address.country                                     Canada
shipping_address.country_code                                    CA
shipping_address.province_code                                   ON
company                                                         NaN
Name: 0, Length: 164, dtype: object

In [118]:
df_orders.iloc[0].keys()

Index(['id', 'admin_graphql_api_id', 'app_id', 'browser_ip',
       'buyer_accepts_marketing', 'cancel_reason', 'cancelled_at',
       'cart_token', 'checkout_id', 'checkout_token',
       ...
       'customer.default_address.country',
       'customer.default_address.province_code',
       'customer.default_address.country_code',
       'customer.default_address.country_name',
       'customer.default_address.default', 'shipping_address.province',
       'shipping_address.country', 'shipping_address.country_code',
       'shipping_address.province_code', 'company'],
      dtype='object', length=164)

In [119]:
df_orders_fixed = df_orders.copy()

df_orders_fixed["order_id"] = df_orders_fixed["id"]

In [120]:
if "customer.id" in df_orders_fixed.columns:
    df_orders_fixed["customer_id"] = df_orders_fixed["customer.id"]

In [121]:
elif "customer" in df_orders_fixed.columns:
    df_orders_fixed["customer_id"] = df_orders_fixed["customer"].apply(
        lambda x: x.get("id") if isinstance(x, dict) else None
    )

SyntaxError: invalid syntax (1061163507.py, line 1)

In [123]:
if "customer.id" in df_orders_fixed.columns:
    df_orders_fixed["customer_id"] = df_orders_fixed["customer.id"]
    elif "customer" in df_orders_fixed.columns:
    df_orders_fixed["customer_id"] = df_orders_fixed["customer"].apply(
        lambda x: x.get("id") if isinstance(x, dict) else None
    )

SyntaxError: invalid syntax (1497501561.py, line 3)

In [124]:
df_orders_fixed = df_orders.copy()

df_orders_fixed["order_id"] = df_orders_fixed["id"]

# safest possible way (works with your dataset)
df_orders_fixed["customer_id"] = df_orders_fixed.get("customer.id")

In [125]:
import pandas as pd

line_items = pd.json_normalize(
    df_orders_fixed.to_dict(orient="records"),
    record_path="line_items",
    meta=[
        "order_id",
        "created_at",
        "total_price",
        "customer_id"
    ],
    errors="ignore"
)

In [126]:
line_items.shape
line_items.head()

,id,admin_graphql_api_id,attributed_staffs,current_quantity,fulfillable_quantity,fulfillment_service,fulfillment_status,gift_card,grams,name,...,price_set.presentment_money.amount,price_set.presentment_money.currency_code,total_discount_set.shop_money.amount,total_discount_set.shop_money.currency_code,total_discount_set.presentment_money.amount,total_discount_set.presentment_money.currency_code,order_id,created_at,total_price,customer_id
0,16345780813898,gid://shopify/LineItem/16345780813898,[],1,1,manual,None,False,0,The Multi-location Snowboard,...,964.00,CAD,0.00,USD,0.00,CAD,6778146586698,2026-04-24T05:43:55-04:00,735.91,9704049770570
1,16345780748362,gid://shopify/LineItem/16345780748362,[],1,1,manual,None,False,4536,The Complete Snowboard - Sunset,...,924.00,CAD,0.00,USD,0.00,CAD,6778146553930,2026-04-24T05:43:45-04:00,3215.75,9704049803338
2,16345780781130,gid://shopify/LineItem/16345780781130,[],1,1,snow-city-warehouse,None,False,0,The 3p Fulfilled Snowboard,...,3472.00,CAD,0.00,USD,0.00,CAD,6778146553930,2026-04-24T05:43:45-04:00,3215.75,9704049803338
3,16345780518986,gid://shopify/LineItem/16345780518986,[],1,1,manual,None,False,4536,The Complete Snowboard - Sunset,...,924.00,CAD,0.00,USD,0.00,CAD,6778146324554,2026-04-24T05:43:31-04:00,706.65,9704049770570
4,16345780355146,gid://shopify/LineItem/16345780355146,[],1,1,manual,None,False,4536,The Complete Snowboard - Powder,...,924.00,CAD,10.16,USD,13.89,CAD,6778146193482,2026-04-24T05:43:17-04:00,1745.68,9704049803338

In [127]:
import json
import pandas as pd

# load raw orders
with open("raw_orders.json", "r") as f:
    raw_orders = json.load(f)

type(raw_orders)

FileNotFoundError: [Errno 2] No such file or directory: 'raw_orders.json'

In [128]:
type(df_orders)
df_orders.shape

(10, 164)

In [129]:
type(df_orders["line_items"].iloc[0])

list

In [130]:
df_orders["line_items"].iloc[0]

[{'id': 16345780813898,
  'admin_graphql_api_id': 'gid://shopify/LineItem/16345780813898',
  'attributed_staffs': [],
  'current_quantity': 1,
  'fulfillable_quantity': 1,
  'fulfillment_service': 'manual',
  'fulfillment_status': None,
  'gift_card': False,
  'grams': 0,
  'name': 'The Multi-location Snowboard',
  'price': '705.19',
  'price_set': {'shop_money': {'amount': '705.19', 'currency_code': 'USD'},
   'presentment_money': {'amount': '964.00', 'currency_code': 'CAD'}},
  'product_exists': True,
  'product_id': 8189224648778,
  'properties': [],
  'quantity': 1,
  'requires_shipping': True,
  'sku': None,
  'taxable': True,
  'title': 'The Multi-location Snowboard',
  'total_discount': '0.00',
  'total_discount_set': {'shop_money': {'amount': '0.00',
    'currency_code': 'USD'},
   'presentment_money': {'amount': '0.00', 'currency_code': 'CAD'}},
  'variant_id': 43538059657290,
  'variant_inventory_management': 'shopify',
  'variant_title': None,
  'vendor': 'forma-active-dev',
  'tax_lines': [],
  'duties': [],
  'discount_allocations': []}]

In [131]:
df_exploded = df_orders.explode("line_items").reset_index(drop=True)

In [132]:
df_exploded.shape

(12, 164)

In [133]:
df_orders.shape

(10, 164)

In [134]:
df_orders["line_items"].apply(type).value_counts()

line_items
<class 'list'>    10
Name: count, dtype: int64

In [135]:
type(df_orders)

pandas.core.frame.DataFrame

In [136]:
df_orders.shape

(10, 164)

In [137]:
df_orders.columns

Index(['id', 'admin_graphql_api_id', 'app_id', 'browser_ip',
       'buyer_accepts_marketing', 'cancel_reason', 'cancelled_at',
       'cart_token', 'checkout_id', 'checkout_token',
       ...
       'customer.default_address.country',
       'customer.default_address.province_code',
       'customer.default_address.country_code',
       'customer.default_address.country_name',
       'customer.default_address.default', 'shipping_address.province',
       'shipping_address.country', 'shipping_address.country_code',
       'shipping_address.province_code', 'company'],
      dtype='object', length=164)

In [138]:
type(df_orders), df_orders.shape

(pandas.core.frame.DataFrame, (10, 164))

In [139]:
type(df_orders["line_items"].iloc[0])
df_orders["line_items"].iloc[0][:1]

[{'id': 16345780813898,
  'admin_graphql_api_id': 'gid://shopify/LineItem/16345780813898',
  'attributed_staffs': [],
  'current_quantity': 1,
  'fulfillable_quantity': 1,
  'fulfillment_service': 'manual',
  'fulfillment_status': None,
  'gift_card': False,
  'grams': 0,
  'name': 'The Multi-location Snowboard',
  'price': '705.19',
  'price_set': {'shop_money': {'amount': '705.19', 'currency_code': 'USD'},
   'presentment_money': {'amount': '964.00', 'currency_code': 'CAD'}},
  'product_exists': True,
  'product_id': 8189224648778,
  'properties': [],
  'quantity': 1,
  'requires_shipping': True,
  'sku': None,
  'taxable': True,
  'title': 'The Multi-location Snowboard',
  'total_discount': '0.00',
  'total_discount_set': {'shop_money': {'amount': '0.00',
    'currency_code': 'USD'},
   'presentment_money': {'amount': '0.00', 'currency_code': 'CAD'}},
  'variant_id': 43538059657290,
  'variant_inventory_management': 'shopify',
  'variant_title': None,
  'vendor': 'forma-active-dev',
  'tax_lines': [],
  'duties': [],
  'discount_allocations': []}]

In [140]:
df_base = df_orders.copy()

df_base["order_id"] = df_base["id"]
df_base["customer_id"] = df_base.get("customer.id")

df_base = df_base[["order_id", "created_at", "total_price", "customer_id", "line_items"]]

df_base.shape, df_base.head(2)

((10, 5),
         order_id                 created_at total_price    customer_id  \
 0  6778146586698  2026-04-24T05:43:55-04:00      735.91  9704049770570
 1  6778146553930  2026-04-24T05:43:45-04:00     3215.75  9704049803338

                                           line_items
 0  [{'id': 16345780813898, 'admin_graphql_api_id'...
 1  [{'id': 16345780748362, 'admin_graphql_api_id'...  )

In [141]:
df_exploded = df_base.explode("line_items").reset_index(drop=True)

df_exploded.shape, type(df_exploded["line_items"].iloc[0])

((12, 5), dict)

In [142]:
line_items = pd.json_normalize(df_exploded["line_items"])

line_items.shape, line_items.columns[:10]

((12, 35),
 Index(['id', 'admin_graphql_api_id', 'attributed_staffs', 'current_quantity',
        'fulfillable_quantity', 'fulfillment_service', 'fulfillment_status',
        'gift_card', 'grams', 'name'],
       dtype='object'))

In [143]:
df_li = df_exploded.drop(columns=["line_items"]).reset_index(drop=True)

df_li = pd.concat([df_li, line_items], axis=1)

df_li.shape

(12, 39)

In [144]:
order_line_items = df_li[[
    "order_id",
    "created_at",
    "product_id",
    "variant_id",
    "title",
    "quantity",
    "price",
    "total_price"
]].copy()

order_line_items["revenue"] = (
    order_line_items["quantity"].astype(float)
    * order_line_items["price"].astype(float)
)

order_line_items.head(), order_line_items.shape

(        order_id                 created_at    product_id    variant_id  \
 0  6778146586698  2026-04-24T05:43:55-04:00  8.189225e+12  4.353806e+13
 1  6778146553930  2026-04-24T05:43:45-04:00  8.189225e+12  4.353806e+13
 2  6778146553930  2026-04-24T05:43:45-04:00  8.189225e+12  4.353806e+13
 3  6778146324554  2026-04-24T05:43:31-04:00  8.189225e+12  4.353806e+13
 4  6778146193482  2026-04-24T05:43:17-04:00  8.189225e+12  4.353806e+13

                           title  quantity    price total_price  revenue
 0  The Multi-location Snowboard         1   705.19      735.91   705.19
 1        The Complete Snowboard         1   675.92     3215.75   675.92
 2    The 3p Fulfilled Snowboard         1  2539.83     3215.75  2539.83
 3        The Complete Snowboard         1   675.93      706.65   675.93
 4        The Complete Snowboard         1   675.92     1745.68   675.92  ,
 (12, 9))

In [145]:
order_line_items = order_line_items.copy()

# enforce correct types
order_line_items["order_id"] = order_line_items["order_id"].astype(str)
order_line_items["product_id"] = order_line_items["product_id"].astype("Int64").astype(str)
order_line_items["variant_id"] = order_line_items["variant_id"].astype("Int64").astype(str)
order_line_items["quantity"] = order_line_items["quantity"].astype(int)
order_line_items["price"] = order_line_items["price"].astype(float)

# final validation
order_line_items.isnull().sum(), order_line_items.dtypes

(order_id       0
 created_at     0
 product_id     0
 variant_id     0
 title          0
 quantity       0
 price          0
 total_price    0
 revenue        0
 dtype: int64,
 order_id        object
 created_at      object
 product_id      object
 variant_id      object
 title           object
 quantity         int64
 price          float64
 total_price     object
 revenue        float64
 dtype: object)

In [146]:
print("rows:", len(order_line_items))
print("unique orders:", order_line_items["order_id"].nunique())
print("unique products:", order_line_items["product_id"].nunique())
print("revenue sum:", order_line_items["revenue"].sum())

rows: 12
unique orders: 10
unique products: 5
revenue sum: 15455.22

In [147]:
# 1. Type safety checks
assert isinstance(final_fact_table, pd.DataFrame)

# 2. Shape sanity
print("shape:", final_fact_table.shape)

# 3. Required columns check
required_cols = [
    "order_id",
    "created_at",
    "product_id",
    "variant_id",
    "title",
    "quantity",
    "price",
    "revenue",
    "total_price"
]

missing = [c for c in required_cols if c not in final_fact_table.columns]
print("missing columns:", missing)
assert len(missing) == 0

# 4. Null checks (critical fields)
print(final_fact_table[["order_id", "product_id", "quantity", "price"]].isna().sum())

# 5. Uniqueness checks
print("unique orders:", final_fact_table["order_id"].nunique())
print("unique products:", final_fact_table["product_id"].nunique())

# 6. Revenue consistency check
calc_revenue = (final_fact_table["quantity"] * final_fact_table["price"].astype(float)).sum()
print("manual revenue check:", calc_revenue)
print("stored revenue:", final_fact_table["revenue"].sum())

# 7. Order coverage check
order_coverage = final_fact_table["order_id"].nunique() / df_orders.shape[0]
print("order coverage:", order_coverage)
\

_IncompleteInputError: incomplete input (396360245.py, line 39)

In [148]:
# 1. Type safety checks
assert isinstance(final_fact_table, pd.DataFrame)

# 2. Shape sanity
print("shape:", final_fact_table.shape)

# 3. Required columns check
required_cols = [
    "order_id",
    "created_at",
    "product_id",
    "variant_id",
    "title",
    "quantity",
    "price",
    "revenue",
    "total_price"
]

missing = [c for c in required_cols if c not in final_fact_table.columns]
print("missing columns:", missing)
assert len(missing) == 0

# 4. Null checks (critical fields)
print(final_fact_table[["order_id", "product_id", "quantity", "price"]].isna().sum())

# 5. Uniqueness checks
print("unique orders:", final_fact_table["order_id"].nunique())
print("unique products:", final_fact_table["product_id"].nunique())

# 6. Revenue consistency check
calc_revenue = (final_fact_table["quantity"] * final_fact_table["price"].astype(float)).sum()
print("manual revenue check:", calc_revenue)
print("stored revenue:", final_fact_table["revenue"].sum())

# 7. Order coverage check
order_coverage = final_fact_table["order_id"].nunique() / df_orders.shape[0]
print("order coverage:", order_coverage)

shape: (12, 9)
missing columns: []
order_id      0
product_id    1
quantity      0
price         0
dtype: int64
unique orders: 10
unique products: 4
manual revenue check: 15455.22
stored revenue: 15455.22
order coverage: 1.0

In [149]:
# isolate problem rows
null_products = final_fact_table[final_fact_table["product_id"].isna()]

print("null product rows:")
display(null_products)

# decide safe handling strategy (Shopify-safe default)
final_fact_table = final_fact_table.dropna(subset=["product_id"]).copy()

# enforce type consistency (important for downstream joins later)
final_fact_table["product_id"] = final_fact_table["product_id"].astype("int64").astype(str)

print("new shape:", final_fact_table.shape)
print("remaining nulls:", final_fact_table["product_id"].isna().sum())

null product rows:

,order_id,created_at,product_id,variant_id,title,quantity,price,revenue,total_price
10,6778144358474,2026-04-24T05:40:47-04:00,NaN,NaN,Custom Snowboard,1,203.37,203.37,234.09

new shape: (11, 9)
remaining nulls: 0

In [150]:
order_line_items = final_fact_table.copy()

# enforce stable dtypes
order_line_items["order_id"] = order_line_items["order_id"].astype(str)
order_line_items["product_id"] = order_line_items["product_id"].astype(str)
order_line_items["quantity"] = order_line_items["quantity"].astype(int)
order_line_items["price"] = order_line_items["price"].astype(float)
order_line_items["revenue"] = order_line_items["revenue"].astype(float)

# final sanity
print(order_line_items.shape)
print(order_line_items.dtypes)
order_line_items.head()

(11, 9)
order_id        object
created_at      object
product_id      object
variant_id     float64
title           object
quantity         int64
price          float64
revenue        float64
total_price     object
dtype: object

,order_id,created_at,product_id,variant_id,title,quantity,price,revenue,total_price
0,6778146586698,2026-04-24T05:43:55-04:00,8189224648778,4.353806e+13,The Multi-location Snowboard,1,705.19,705.19,735.91
1,6778146553930,2026-04-24T05:43:45-04:00,8189224517706,4.353806e+13,The Complete Snowboard,1,675.92,675.92,3215.75
2,6778146553930,2026-04-24T05:43:45-04:00,8189224714314,4.353806e+13,The 3p Fulfilled Snowboard,1,2539.83,2539.83,3215.75
3,6778146324554,2026-04-24T05:43:31-04:00,8189224517706,4.353806e+13,The Complete Snowboard,1,675.93,675.93,706.65
4,6778146193482,2026-04-24T05:43:17-04:00,8189224517706,4.353806e+13,The Complete Snowboard,1,675.92,675.92,1745.68

In [151]:
order_line_items.to_csv("order_line_items.csv", index=False)

In [152]:
df_orders.to_csv("orders_raw_flat.csv", index=False)

In [153]:
import os

print(os.getcwd())

C:\Users\user\Desktop\Data_Analytics_Project3\Jupyter notebooks

In [154]:
import numpy as np
import pandas as pd

base_orders = df_orders.copy()

# how much expansion
MULTIPLIER = 30   # 10 orders → ~300 orders

df_expanded_orders = pd.concat([base_orders] * MULTIPLIER, ignore_index=True)

# regenerate unique order IDs (critical)
df_expanded_orders["order_id"] = "SIM-" + df_expanded_orders.index.astype(str)

print(df_expanded_orders.shape)
print(df_expanded_orders["order_id"].nunique())

(300, 165)
300

In [155]:
expanded_line_items = []

for _, order in df_expanded_orders.iterrows():
    for item in order["line_items"]:
        expanded_line_items.append({
            "order_id": order["order_id"],
            "created_at": order["created_at"],
            "product_id": item.get("product_id"),
            "variant_id": item.get("variant_id"),
            "title": item.get("title"),
            "quantity": item.get("quantity"),
            "price": float(item.get("price", 0)),
        })

df_line_items_expanded = pd.DataFrame(expanded_line_items)

# compute revenue
df_line_items_expanded["revenue"] = (
    df_line_items_expanded["quantity"] * df_line_items_expanded["price"]
)

print(df_line_items_expanded.shape)
df_line_items_expanded.head()

(360, 8)

,order_id,created_at,product_id,variant_id,title,quantity,price,revenue
0,SIM-0,2026-04-24T05:43:55-04:00,8.189225e+12,4.353806e+13,The Multi-location Snowboard,1,705.19,705.19
1,SIM-1,2026-04-24T05:43:45-04:00,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.92,675.92
2,SIM-1,2026-04-24T05:43:45-04:00,8.189225e+12,4.353806e+13,The 3p Fulfilled Snowboard,1,2539.83,2539.83
3,SIM-2,2026-04-24T05:43:31-04:00,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.93,675.93
4,SIM-3,2026-04-24T05:43:17-04:00,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.92,675.92

In [156]:
print("orders:", df_expanded_orders["order_id"].nunique())
print("line items:", df_line_items_expanded.shape[0])
print("products:", df_line_items_expanded["product_id"].nunique())
print("revenue sum:", df_line_items_expanded["revenue"].sum())

orders: 300
line items: 360
products: 4
revenue sum: 463656.60000000003

In [157]:
orders_clean = df_expanded_orders.copy()

orders_clean = orders_clean[[
    "order_id",
    "created_at",
    "customer.id",
    "financial_status",
    "total_price"
]].rename(columns={
    "customer.id": "customer_id"
})

orders_clean["created_at"] = pd.to_datetime(orders_clean["created_at"])

orders_clean.shape
orders_clean.head()

,order_id,created_at,customer_id,financial_status,total_price
0,SIM-0,2026-04-24 05:43:55-04:00,9704049770570,paid,735.91
1,SIM-1,2026-04-24 05:43:45-04:00,9704049803338,paid,3215.75
2,SIM-2,2026-04-24 05:43:31-04:00,9704049770570,paid,706.65
3,SIM-3,2026-04-24 05:43:17-04:00,9704049803338,paid,1745.68
4,SIM-4,2026-04-24 05:42:05-04:00,9704049803338,paid,1247.38

In [158]:
order_line_items = df_line_items_expanded.copy()

order_line_items = order_line_items[[
    "order_id",
    "created_at",
    "product_id",
    "variant_id",
    "title",
    "quantity",
    "price",
    "revenue"
]]

order_line_items.shape
order_line_items.head()

,order_id,created_at,product_id,variant_id,title,quantity,price,revenue
0,SIM-0,2026-04-24T05:43:55-04:00,8.189225e+12,4.353806e+13,The Multi-location Snowboard,1,705.19,705.19
1,SIM-1,2026-04-24T05:43:45-04:00,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.92,675.92
2,SIM-1,2026-04-24T05:43:45-04:00,8.189225e+12,4.353806e+13,The 3p Fulfilled Snowboard,1,2539.83,2539.83
3,SIM-2,2026-04-24T05:43:31-04:00,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.93,675.93
4,SIM-3,2026-04-24T05:43:17-04:00,8.189225e+12,4.353806e+13,The Complete Snowboard,1,675.92,675.92

In [159]:
products_variants = order_line_items[[
    "product_id",
    "variant_id",
    "title",
    "price"
]].drop_duplicates()

products_variants.shape
products_variants.head()

     product_id    variant_id                         title    price
0  8.189225e+12  4.353806e+13  The Multi-location Snowboard   705.19
1  8.189225e+12  4.353806e+13        The Complete Snowboard   675.92
2  8.189225e+12  4.353806e+13    The 3p Fulfilled Snowboard  2539.83
3  8.189225e+12  4.353806e+13        The Complete Snowboard   675.93
4  8.189225e+12  4.353806e+13        The Complete Snowboard   675.92

In [160]:
customers_clean = orders_clean.groupby("customer_id").agg(
    first_order=("created_at", "min"),
    total_orders=("order_id", "nunique"),
    lifetime_value=("total_price", "sum")
).reset_index()

customers_clean["cohort_month"] = customers_clean["first_order"].dt.to_period("M").astype(str)

customers_clean.shape
customers_clean.head()

C:\Users\user\AppData\Local\Temp\ipykernel_8824\2736921513.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  customers_clean["cohort_month"] = customers_clean["first_order"].dt.to_period("M").astype(str)

,customer_id,first_order,total_orders,lifetime_value,cohort_month
0,9704049770570,2026-04-24 05:41:56-04:00,90,735.91706.652058.48735.91706.652058.48735.9170...,2026-04
1,9704049803338,2026-04-24 05:40:47-04:00,120,3215.751745.681247.38234.093215.751745.681247....,2026-04
2,9704074182730,2026-04-24 05:40:25-04:00,90,885.952799.80885.95885.952799.80885.95885.9527...,2026-04

In [161]:
print("=== SHAPES ===")
print("orders_clean:", orders_clean.shape)
print("order_line_items:", order_line_items.shape)
print("products_variants:", products_variants.shape)
print("customers_clean:", customers_clean.shape)

print("\n=== ROW COVERAGE ===")
print("unique orders (orders_clean):", orders_clean["order_id"].nunique())
print("unique orders (line_items):", order_line_items["order_id"].nunique())

print("\n=== DIMENSION COUNTS ===")
print("unique customers:", customers_clean["customer_id"].nunique())
print("unique products:", products_variants["product_id"].nunique())

print("\n=== JOIN SANITY ===")
order_match = set(order_line_items["order_id"]).issubset(set(orders_clean["order_id"]))
customer_match = set(orders_clean["customer_id"]).issubset(set(customers_clean["customer_id"]))
product_match = set(order_line_items["product_id"].astype(str)).issubset(set(products_variants["product_id"].astype(str)))

print("orders ↔ line_items:", order_match)
print("orders ↔ customers:", customer_match)
print("line_items ↔ products:", product_match)

=== SHAPES ===
orders_clean: (300, 5)
order_line_items: (360, 8)
products_variants: (11, 4)
customers_clean: (3, 5)

=== ROW COVERAGE ===
unique orders (orders_clean): 300
unique orders (line_items): 300

=== DIMENSION COUNTS ===
unique customers: 3
unique products: 4

=== JOIN SANITY ===
orders ↔ line_items: True
orders ↔ customers: True
line_items ↔ products: True

In [162]:
import numpy as np

# target number of customers
TARGET_CUSTOMERS = 12

# extract current unique customers
existing_customers = orders_clean["customer_id"].dropna().unique()

# generate synthetic customer pool
new_customers = [f"CUST-{i}" for i in range(TARGET_CUSTOMERS)]

# map old customers → new expanded pool
np.random.seed(42)

customer_map = {
    old: np.random.choice(new_customers)
    for old in existing_customers
}

# apply mapping to orders
orders_clean["customer_id"] = orders_clean["customer_id"].map(customer_map)

print("new unique customers:", orders_clean["customer_id"].nunique())
print(orders_clean["customer_id"].value_counts().head())

new unique customers: 3
customer_id
CUST-3     120
CUST-6      90
CUST-10     90
Name: count, dtype: int64

In [163]:
customers_clean = orders_clean.groupby("customer_id").agg(
    first_order=("created_at", "min"),
    total_orders=("order_id", "nunique"),
    lifetime_value=("total_price", "sum")
).reset_index()

customers_clean["cohort_month"] = customers_clean["first_order"].dt.to_period("M").astype(str)

customers_clean.shape
customers_clean.head()

C:\Users\user\AppData\Local\Temp\ipykernel_8824\2736921513.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  customers_clean["cohort_month"] = customers_clean["first_order"].dt.to_period("M").astype(str)

,customer_id,first_order,total_orders,lifetime_value,cohort_month
0,CUST-10,2026-04-24 05:40:25-04:00,90,885.952799.80885.95885.952799.80885.95885.9527...,2026-04
1,CUST-3,2026-04-24 05:40:47-04:00,120,3215.751745.681247.38234.093215.751745.681247....,2026-04
2,CUST-6,2026-04-24 05:41:56-04:00,90,735.91706.652058.48735.91706.652058.48735.9170...,2026-04

In [164]:
print("customers:", customers_clean["customer_id"].nunique())
print("orders:", orders_clean["order_id"].nunique())

print("join integrity:",
      set(orders_clean["customer_id"]).issubset(set(customers_clean["customer_id"])))

customers: 3
orders: 300
join integrity: True

In [165]:
import numpy as np

# target customer count
TARGET_CUSTOMERS = 12

# create synthetic customer IDs
customer_pool = [f"CUST-{i:03d}" for i in range(TARGET_CUSTOMERS)]

# assign customers to orders using controlled randomness
np.random.seed(42)

orders_clean["customer_id"] = np.random.choice(
    customer_pool,
    size=len(orders_clean),
    replace=True
)

print("new unique customers:", orders_clean["customer_id"].nunique())
print(orders_clean["customer_id"].value_counts().head())

new unique customers: 12
customer_id
CUST-011    37
CUST-006    31
CUST-000    28
CUST-008    27
CUST-007    25
Name: count, dtype: int64

In [166]:
customers_clean = orders_clean.groupby("customer_id").agg(
    first_order=("created_at", "min"),
    total_orders=("order_id", "nunique"),
    lifetime_value=("total_price", "sum")
).reset_index()

customers_clean["cohort_month"] = customers_clean["first_order"].dt.to_period("M").astype(str)

customers_clean.shape
customers_clean.head()

C:\Users\user\AppData\Local\Temp\ipykernel_8824\2736921513.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  customers_clean["cohort_month"] = customers_clean["first_order"].dt.to_period("M").astype(str)

,customer_id,first_order,total_orders,lifetime_value,cohort_month
0,CUST-000,2026-04-24 05:40:25-04:00,28,885.95706.652799.80885.951247.38735.911247.382...,2026-04
1,CUST-001,2026-04-24 05:40:25-04:00,20,885.951745.68735.911247.38885.95885.95706.6523...,2026-04
2,CUST-002,2026-04-24 05:40:25-04:00,25,2799.80885.95234.091745.682058.48885.95885.957...,2026-04
3,CUST-003,2026-04-24 05:40:47-04:00,23,3215.751745.683215.753215.75735.91234.093215.7...,2026-04
4,CUST-004,2026-04-24 05:40:25-04:00,22,1247.38706.65234.092058.481247.382799.80234.09...,2026-04

In [167]:
print("customers:", customers_clean["customer_id"].nunique())
print("orders:", orders_clean["order_id"].nunique())

print("order → customer integrity:",
      set(orders_clean["customer_id"]).issubset(set(customers_clean["customer_id"])))

customers: 12
orders: 300
order → customer integrity: True

In [168]:
print("=== SHAPES ===")
print("orders_clean:", orders_clean.shape)
print("order_line_items:", order_line_items.shape)
print("customers_clean:", customers_clean.shape)
print("products_variants:", products_variants.shape)

print("\n=== PRIMARY KEY CHECKS ===")
print("orders unique:", orders_clean["order_id"].nunique())
print("line_items unique orders:", order_line_items["order_id"].nunique())
print("customers unique:", customers_clean["customer_id"].nunique())
print("products unique:", products_variants["product_id"].nunique())

print("\n=== NULL CHECKS ===")
print(orders_clean.isna().sum().sum(),
      order_line_items.isna().sum().sum(),
      customers_clean.isna().sum().sum(),
      products_variants.isna().sum().sum())

print("\n=== JOIN INTEGRITY ===")
print("orders → customers:",
      set(orders_clean["customer_id"]).issubset(set(customers_clean["customer_id"])))

print("line_items → products:",
      set(order_line_items["product_id"]).issubset(set(products_variants["product_id"])))

=== SHAPES ===
orders_clean: (300, 5)
order_line_items: (360, 8)
customers_clean: (12, 5)
products_variants: (11, 4)

=== PRIMARY KEY CHECKS ===
orders unique: 300
line_items unique orders: 300
customers unique: 12
products unique: 4

=== NULL CHECKS ===
0 60 0 2

=== JOIN INTEGRITY ===
orders → customers: True
line_items → products: False

In [169]:
# normalize types BEFORE checking join integrity
order_line_items["product_id"] = order_line_items["product_id"].astype("float64").astype("Int64")
products_variants["product_id"] = products_variants["product_id"].astype("float64").astype("Int64")

# check missing matches
missing_products = set(order_line_items["product_id"]) - set(products_variants["product_id"])

len(missing_products), list(missing_products)[:10]

(0, [])

In [170]:
# normalize types BEFORE checking join integrity
order_line_items["product_id"] = order_line_items["product_id"].astype("float64").astype("Int64")
products_variants["product_id"] = products_variants["product_id"].astype("float64").astype("Int64")

# check missing matches
missing_products = set(order_line_items["product_id"]) - set(products_variants["product_id"])

len(missing_products), list(missing_products)[:10]

(0, [])

In [171]:
missing_products = set(order_line_items["product_id"]) - set(products_variants["product_id"])

print("remaining missing:", len(missing_products))
print("join integrity:", len(missing_products) == 0)

remaining missing: 0
join integrity: True

In [172]:
order_line_items.to_csv("order_line_items.csv", index=False)
orders_clean.to_csv("orders_clean.csv", index=False)
customers_clean.to_csv("customers_clean.csv", index=False)
products_variants.to_csv("products_variants.csv", index=False)